# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-29 22:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
        ('my_book', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('content', models.CharField(max_length=5000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('favorite', models.ManyToManyField(related_name='favoriteQuotes', to='login.User')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quote', to='login.User')),
            ],
        ),
        migrations.RemoveField(
            model_name='quotes',
            name='favorite',
        ),
        migrations.RemoveField(
            model_name='quotes',
            name='user_id',
        ),
        migrations.DeleteModel(
            name='Quotes',
        ),
    ]
