# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-30 00:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_book', '0003_auto_20170630_0010'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quote',
            name='favorite',
        ),
    ]
